### ISSUE TITLE
The sentence start "<s>" and end "</s>"

### ISSUE THREAD

**Issue by navta** [vsiivola/variKN#9]
Hi,

I'd like to modify the source code, so that the sentence start "<s>" and end "</s>" added automatically. Is it easy to do so? Could you give me a hint where/what to change?

Thank you!

**Comment by vsiivola** [comment]
Hi,

The data is read in at Storeage_tmpl.hh::read(). You would have to replace the fscanf with something that reads one line at a time and adds the beginning and end-of-sentence markers.

Vesa

**Comment by vsiivola** [comment]
Hmm, it might have been more complicated than that. I'll take a second look.

**Comment by vsiivola** [comment]
Ok, it's been a while since a last looked at that code. It seems to be a bit tricky, partly because of optimizations and partly because of bad design. I think if you can fit all the data in the memory and do not need the --smallmemory flag, the change in Storage_tmpl.hh::read() may suffice. If you are using the --smallmemory code path, you need to additionally change Storage_tmpl.hh:init_fsl_file() and MultiOrderCounts_tmpl.hh:InitializeCountsFromText(). Hopefully that covers it, this is based on a quick read of the code.

**Comment by vsiivola** [comment]
Ah, still more. The above should cover it for the model estimation, for perplexity evaluation there are still PreplexityFuncs:logprob_file() and at least unit tests use InterKN_tmpl.hh:logprob_file(). 

This is a good candidate for a code cleanup, definitely.

**Comment by navta** [comment]
Thank you very much!
